name: vm_service_client
version: 0.2.2
description: A client for the Dart VM service.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/vm_service_client

environment:
  sdk: '>=1.16.0 <2.0.0'

dependencies:
  async: '^1.7.0'
  collection: '>=0.9.2 <2.0.0'
  json_rpc_2: '^2.0.0'
  pub_semver: '^1.0.0'
  source_span: '^1.1.3'
  stack_trace: '^1.5.0'
  stream_channel: '^1.1.0'
  web_socket_channel: '^1.0.0'

dev_dependencies:
  test: '^0.12.0'
