name: vm_service_client
version: 0.2.6+3
description: A client for the Dart VM service.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/vm_service_client

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  async: ^2.0.0
  collection: ^1.5.0
  json_rpc_2: ^2.0.0
  pub_semver: ^1.0.0
  source_span: ^1.4.0
  stack_trace: ^1.5.0
  stream_channel: ">=1.1.0 <3.0.0"
  web_socket_channel: ^1.0.0

dev_dependencies:
  test: ^1.6.0
